development:
    secret_key_base: "516174a77903c57a9de631804357ef8adc97e753de4f17926669c6810a92bc968fdcabf6cefd702cf10bd01887a6ef93c2ae98f21eb13bbeb0e0528e77fc1f18"

    #stripe_pri*vate_key_pattern: "sk_(test|live)_.{24,200}"
    #stripe_publishable_key_pattern: "pk_(test|live)_.{24,200}"
    #app_encryption_key: "2617463e32b65ec6645b3cb661f96f6f2ab608c18ac930ee1295a1c1170987ed"

    # mail_delivery_method: "sendmail"
    # Google login
    google_client_secret: "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" #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 #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
    google_client_id: "27470802024-3pc0hl49186hbikj5gqa3hu1qsm8cvnd.apps.googleusercontent.com" #27470802024-bn3dsuh21kp1007hkkli6vd3qmou2qii.apps.googleusercontent.com #27470802024-3pc0hl49186hbikj5gqa3hu1qsm8cvnd.apps.googleusercontent.com #842421732181-ah45g1364v6hhi81kub41ehn2q7b5uk1.apps.googleusercontent.com ##11340329664-bqh0hjb9o9c09uhv5pne5jv90rgouriu.apps.googleusercontent.com

    mail_delivery_method: "smtp"
    smtp_email_address: 'smtp.sendgrid.net'
    smtp_email_port: 587
    smtp_email_domain: 'sendgrid.net'
    smtp_email_user_name: 'apikey'
    smtp_email_password: ''


    sharetribe_mail_from_address: 'team@telemartuae.com' #"info@pdx.climate.action.hub"
    skip_email_confirmation: false
    icon_pack: "ss-pika"
    #clp_static_enabled: true
    show_landing_page_admin: true


    #google_maps_key: "AIzaSyBXcUCmBDBkYwMkuV6QRP6oKM37MzfkGew"
    active_storage_service: "local"
    google_maps_key: AIzaSyCLHRjKWaABrUYwzGYuCxD-6MtJ3rNTP60 #AIzaSyCuvXzGEIcHICNqAD0xfUFDZ7V0PCIKUwY #AIzaSyCLHRjKWaABrUYwzGYuCxD-6MtJ3rNTP60 #"AIzaSyDVK_u8Of88RckbXsQZNIWrQ4o6ScUhcs4"

    stripe_charges_mode: :destination
    stripe_payout_delay: 7.5
    stripe_expiration_period: 3
    stripe_private_key_pattern: "sk_(test|live)_.{24}"
    stripe_publishable_key_pattern: "pk_(test|live)_.{24}"
    stripe_max_booking_date: 85
    active_storage_service: local
    app_encryption_key: "2617463e32b65ec6645b3cb661f9686f2ab608c18ac930ee1295a1c1170504ed"
    feature_stripe_publishable_key: "pk_live_444VTRmfZNkrtjG71ZfORrop00BfPpHE4c" ####pk_test_51HDSMpIefWskAZFZn4bTQaMY7X2MJIj8uKngHe6huKQQbzYgYnjbF6nLjIpkUa1wnXPTvbW5YwBWq1YkFb12Wevg00xl0HXoor
    feature_stripe_private_key: "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" ###sk_test_51HDSMpIefWskAZFZOqSEVY40NobPopwARkKD05sRnRxF8MlIuNzXGynTdc4qyGhLcfpSL1UB5wsXpS4xUiq96E30003cLDt5E4
    #### sharetempus_key: sk_test_qjCbbvCqpZmKNmRsz2pSorDM
    stripe_key: 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
    #sharetempus_base_url: https://api.sharetempus.com/v1
production:
    secret_key_base: "516174a77903c57a9de631804357ef8adc97e753de4f17926669c6810a92bc968fdcabf6cefd702cf10bd01887a6ef93c2ae98f21eb13bbeb0e0528e77fc1f18"

    #stripe_pri*vate_key_pattern: "sk_(test|live)_.{24,200}"
    #stripe_publishable_key_pattern: "pk_(test|live)_.{24,200}"
    #app_encryption_key: "2617463e32b65ec6645b3cb661f96f6f2ab608c18ac930ee1295a1c1170987ed"

    # mail_delivery_method: "sendmail"
    # Google login
    google_client_secret: "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" #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 #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
    google_client_id: "27470802024-3pc0hl49186hbikj5gqa3hu1qsm8cvnd.apps.googleusercontent.com" #27470802024-bn3dsuh21kp1007hkkli6vd3qmou2qii.apps.googleusercontent.com #27470802024-3pc0hl49186hbikj5gqa3hu1qsm8cvnd.apps.googleusercontent.com #842421732181-ah45g1364v6hhi81kub41ehn2q7b5uk1.apps.googleusercontent.com ##11340329664-bqh0hjb9o9c09uhv5pne5jv90rgouriu.apps.googleusercontent.com

    mail_delivery_method: "smtp"
    smtp_email_address: 'smtp.sendgrid.net'
    smtp_email_port: 587
    smtp_email_domain: 'sendgrid.net'
    smtp_email_user_name: 'apikey'
    smtp_email_password: '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' #'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' #'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' #'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'
    
    #'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'
    #'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'


    sharetribe_mail_from_address: 'team@orclimatehub.org' #"info@pdx.climate.action.hub"
    skip_email_confirmation: false
    icon_pack: "ss-pika"
    #clp_static_enabled: true
    show_landing_page_admin: true


    #google_maps_key: "AIzaSyBXcUCmBDBkYwMkuV6QRP6oKM37MzfkGew"
    active_storage_service: "local"
    google_maps_key: AIzaSyCLHRjKWaABrUYwzGYuCxD-6MtJ3rNTP60 #"AIzaSyDVK_u8Of88RckbXsQZNIWrQ4o6ScUhcs4"

    stripe_charges_mode: :destination
    stripe_payout_delay: 7.5
    stripe_expiration_period: 3
    stripe_private_key_pattern: "sk_(test|live)_.{24}"
    stripe_publishable_key_pattern: "pk_(test|live)_.{24}"
    stripe_max_booking_date: 85
    active_storage_service: local
    app_encryption_key: "2617463e32b65ec6645b3cb661f9686f2ab608c18ac930ee1295a1c1170504ed"
    feature_stripe_publishable_key: "pk_live_444VTRmfZNkrtjG71ZfORrop00BfPpHE4c" ####pk_test_51HDSMpIefWskAZFZn4bTQaMY7X2MJIj8uKngHe6huKQQbzYgYnjbF6nLjIpkUa1wnXPTvbW5YwBWq1YkFb12Wevg00xl0HXoor
    feature_stripe_private_key: "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" ###sk_test_51HDSMpIefWskAZFZOqSEVY40NobPopwARkKD05sRnRxF8MlIuNzXGynTdc4qyGhLcfpSL1UB5wsXpS4xUiq96E30003cLDt5E4
    #### sharetempus_key: sk_test_qjCbbvCqpZmKNmRsz2pSorDM
    stripe_key: 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
    #sharetempus_base_url: https://api.sharetempus.com/v1
